version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  rotate_log:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: 'bot.log'
    maxBytes: 16777216
    backupCount: 6
root:
  level: INFO
  handlers: [console, rotate_log]
