version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
loggers:
  euphoria.state_machines.nick_and_auth:
    level: DEBUG
    handlers: [console]
    propagate: no
  euphoria.client:
    level: INFO
    handlers: [console]
    propagate: no
  euphoria.bot:
    level: DEBUG
    handlers: [console]
    propagate: no
root:
  level: INFO
  handlers: [console]
